title: Kimia Nadjahi
owner: Kimia Nadjahi
email:
description: Kimia Nadjahi's website
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://kimiandj.github.io" # the base hostname & protocol for your site, e.g. http://example.com
language: en
twitter_username:
github_username:
disqus_username: 
# Build settings
markdown: kramdown
theme: minima

permalink: /:year/:month/:day/:title/

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->
